name: Shaun Webb Golf
favicon: null
layout_spectrum: 0.09874707856215537
typography_spectrum: 0.5265554240904748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6810449108015746
  lightness: 0.6130005032755435
  saturation: 0.38051253207959235
  rhythmicContrast: 0.2013271830510348
purpose: []
